server:
  port: 8080

spring:
  application:
    name: hola-mundo-thymeleaf

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/mi_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true